apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-monitor-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: py-monitor
  template:
    metadata:
      labels:
        app: py-monitor
    spec:
      containers:
        - name: py-monitor
          image: yash5090/py-monitor:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
